//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScaleMonitor.ScaleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Balance_Result", Namespace="http://schemas.datacontract.org/2004/07/ScaleService.Shared")]
    [System.SerializableAttribute()]
    public partial class Balance_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Scale_ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Scale_TimeoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitOfMesureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Scale_Model {
            get {
                return this.Scale_ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.Scale_ModelField, value) != true)) {
                    this.Scale_ModelField = value;
                    this.RaisePropertyChanged("Scale_Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Scale_Timeout {
            get {
                return this.Scale_TimeoutField;
            }
            set {
                if ((object.ReferenceEquals(this.Scale_TimeoutField, value) != true)) {
                    this.Scale_TimeoutField = value;
                    this.RaisePropertyChanged("Scale_Timeout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitOfMesure {
            get {
                return this.UnitOfMesureField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitOfMesureField, value) != true)) {
                    this.UnitOfMesureField = value;
                    this.RaisePropertyChanged("UnitOfMesure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((object.ReferenceEquals(this.WeightField, value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ports", Namespace="http://schemas.datacontract.org/2004/07/ScaleService.Shared")]
    [System.SerializableAttribute()]
    public partial class Ports : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string port_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string port_Name {
            get {
                return this.port_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.port_NameField, value) != true)) {
                    this.port_NameField = value;
                    this.RaisePropertyChanged("port_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScaleService.IScaleService")]
    public interface IScaleService {
        
        [System.ServiceModel.Web.WebGet]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScaleService/Get_Weight", ReplyAction="http://tempuri.org/IScaleService/Get_WeightResponse")]
        ScaleMonitor.ScaleService.Balance_Result[] Get_Weight();

        [System.ServiceModel.Web.WebGet]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScaleService/Get_Available_Ports", ReplyAction="http://tempuri.org/IScaleService/Get_Available_PortsResponse")]
        ScaleMonitor.ScaleService.Ports[] Get_Available_Ports();

        [System.ServiceModel.Web.WebGet]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScaleService/Set_Device", ReplyAction="http://tempuri.org/IScaleService/Set_DeviceResponse")]
        void Set_Device(string Port_Name, string Device_Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScaleServiceChannel : ScaleMonitor.ScaleService.IScaleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScaleServiceClient : System.ServiceModel.ClientBase<ScaleMonitor.ScaleService.IScaleService>, ScaleMonitor.ScaleService.IScaleService {
        
        public ScaleServiceClient() {
        }
        
        public ScaleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScaleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScaleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScaleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ScaleMonitor.ScaleService.Balance_Result[] Get_Weight() {
            return base.Channel.Get_Weight();
        }
        
        public ScaleMonitor.ScaleService.Ports[] Get_Available_Ports() {
            return base.Channel.Get_Available_Ports();
        }
        
        public void Set_Device(string Port_Name, string Device_Name) {
            base.Channel.Set_Device(Port_Name, Device_Name);
        }
    }
}
